"""Build a combined California grocery map data file.

Merges:
  1. Existing MilkPEP/TDA stores from processor_map_data.json (CA only)
  2. New SNAP-authorized grocery destinations from ca_snap_grocers.csv

Deduplication: if a SNAP store's normalized address matches an existing
MilkPEP/TDA store, the records are merged (SNAP source flag added) rather
than duplicated.

Output: data/ca_grocer_map_data.json
"""
import csv
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).parent
DATA_DIR = ROOT / "data"
EXISTING_PATH = DATA_DIR / "processor_map_data.json"
SNAP_CSV_PATH = DATA_DIR / "ca_snap_grocers.csv"
OUTPUT_PATH = DATA_DIR / "ca_grocer_map_data.json"


def normalize_addr(addr: str, city: str) -> str:
    """Build a stable address key for dedup matching."""
    parts = [
        re.sub(r"[^a-z0-9]", "", (addr or "").lower()),
        re.sub(r"[^a-z0-9]", "", (city or "").lower()),
    ]
    return "|".join(p for p in parts if p)


def main() -> None:
    # --- Load existing MilkPEP/TDA stores, filter to CA ---
    with EXISTING_PATH.open() as f:
        existing = json.load(f)

    ca_stores = [s for s in existing["stores"] if s.get("state") == "CA"]

    # Add store_type for existing stores so the filter dimension is uniform
    for s in ca_stores:
        s["store_type"] = "MilkPEP/TDA"

    # Build address index for dedup
    addr_index: dict[str, int] = {}
    for i, s in enumerate(ca_stores):
        key = normalize_addr(s.get("addr", ""), s.get("city", ""))
        if key:
            addr_index[key] = i

    # --- Load SNAP grocers ---
    snap_stores = []
    with SNAP_CSV_PATH.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            lat = float(row["lat"]) if row.get("lat") else None
            lon = float(row["lon"]) if row.get("lon") else None
            if lat is None or lon is None:
                continue

            store_type = row.get("store_type", "").strip()
            store_name = row.get("store_name", "").strip()
            addr = row.get("address", "").strip()
            city = row.get("city", "").strip()

            record = {
                "id": f"SNAP|{row['record_id']}",
                "sn": row.get("record_id", ""),
                "banner": store_name,
                "holding_co": "",
                "processor": "",
                "owner": "",
                "addr": addr,
                "city": city,
                "state": "CA",
                "zip": row.get("zip", "").strip(),
                "lat": lat,
                "lon": lon,
                "region": "West",
                "store_type": store_type,
                "banner_group": "Misc.",
            }

            # Check for address match with existing MilkPEP/TDA store
            addr_key = normalize_addr(addr, city)
            if addr_key and addr_key in addr_index:
                idx = addr_index[addr_key]
                existing_rec = ca_stores[idx]
                # Mark as also in SNAP, keep existing record
                existing_rec["store_type"] = "MilkPEP/TDA + SNAP"
                # Don't add the SNAP record — it's a dup
                continue

            snap_stores.append(record)

    all_stores = ca_stores + snap_stores

    # --- Assign banner_group based on normalized store name frequency ---
    # Many SNAP stores append a store number to the name (e.g.
    # "Whole Foods Market 10045"), so raw banner counts never reach 10.
    # We normalize by stripping trailing numbers to group chains together.
    # Any normalized name with 3+ locations gets its own banner_group
    # filter row. Everything else stays "Misc."
    def normalize_banner(name: str) -> str:
        name = (name or "").strip()
        # Strip # prefixed store numbers: "Northgate #03" -> "Northgate"
        # Also handle "FOODS CO #784 784" -> "Foods Co"
        name = re.sub(r"\s*#\s*\d+(\s+\d+)?\s*$", "", name)
        # Strip T- prefixed store numbers: "Target Store T-1234" -> "Target Store"
        name = re.sub(r"\s+T-?\d+\s*$", "", name, flags=re.IGNORECASE)
        # Strip trailing store numbers (1+ digits) UNLESS the brand
        # name itself starts with a number (e.g. "99 Ranch Market", "168 Market")
        if not re.match(r"^\d", name):
            name = re.sub(r"\s+\d+\s*$", "", name)
        else:
            # For digit-prefixed brands, strip trailing numbers after the brand name
            # "99 Ranch Market 38" -> "99 Ranch Market"
            name = re.sub(r"\s+\d{2,}\s*$", "", name)
        # Title-case for consistent grouping: "FOOD 4 LESS" -> "Food 4 Less"
        name = name.title().replace("&", "&").replace("'S", "'s")
        # Strip trailing period after Co: "Foods Co." -> "Foods Co"
        name = re.sub(r"\.$", "", name).strip()
        # Strip corporate suffixes: "Super A Foods Inc" -> "Super A Foods"
        name = re.sub(r"\s+(Inc|Llc|Corp|Corporation)\.?\s*$", "", name, flags=re.IGNORECASE).strip()
        # Normalize plural/singular: "Supermarkets" -> "Supermarket",
        # "Markets" -> "Market" — handle Supermarkets first to avoid
        # "SuperMarket" case artifacts from partial replacement
        name = re.sub(r"(?i)supermarkets$", "Supermarket", name)
        name = re.sub(r"(?i)markets$", "Market", name)
        # Fix missing apostrophes in known brand names
        apostrophe_fixes = {
            "Gelsons Market": "Gelson's Market",
            "Raleys": "Raley's",
            "Mollie Stones Market": "Mollie Stone's Market",
            "Mollie Stone'S Markets": "Mollie Stone's Market",
            "Mollie Stone'S Tower Market": "Mollie Stone's Market",
            "Mollie Stones Market": "Mollie Stone's Market",
            "Jons Market": "Jons Market",
            "Jons Marketplace": "Jons Market",
            "Lunardis Market": "Lunardi's Market",
            "Olivers Market": "Oliver's Market",
            "Lolas Market": "Lola's Market",
            "Joes Market": "Joe's Market",
            "Jerrys Market": "Jerry's Market",
            "Harrys Market": "Harry's Market",
            "Johns Market": "John's Market",
            "Tonys Market": "Tony's Market",
            "Youngs Market": "Young's Market",
            "Bills Market": "Bill's Market",
            "Ray'S Food Place": "Ray's Food Place",
        }
        name = apostrophe_fixes.get(name, name)
        # Fuzzy prefix matching for chains with city/location names embedded.
        # e.g. "Grocery Outlet Of Altadena" -> "Grocery Outlet"
        prefix_chains = [
            "Grocery Outlet",
            "Smart & Final Store",
            "Smart & Final Stores",
            "La Superior",
        ]
        for prefix in prefix_chains:
            if name.lower().startswith(prefix.lower()):
                name = prefix
                break
        # Merge known aliases — different names for the same chain
        aliases = {
            "Target Store": "Target",
            "Ralphs Fresh Fare": "Ralphs",
            "Ralphs Grocery Company": "Ralphs",
            "Ralphs Grocery": "Ralphs",
            "Ralphs Grocery Co.": "Ralphs",
            "Ralphs Grocery Co": "Ralphs",
            "Ralph's Grocery": "Ralphs",
            "Primetime": "Primetime Nutrition",
            "Prime Time Nutrition": "Primetime Nutrition",
            "Walmart Neighborhood Market": "Walmart",
            "Walmart Supercenter": "Walmart",
            "Northgate": "Northgate Market",
            "Chavez Supermarket": "Chavez Supermarket",
            "Super Chavez Market": "Chavez Supermarket",
            "Andronicos Community Market": "Andronico's",
            "Andronicos Market": "Andronico's",
            "Sf Supermarket": "SF Supermarket",
            "Mother's Market & Kitchen": "Mother's Market",
            "Cardenas Market": "Cardenas",
            "Island Pacific Seafood Market": "Island Pacific Supermarket",
            "Pak N Save": "Pak 'N Save",
            "Pak 'N Save": "Pak 'N Save",
            "Costco": "Costco Wholesale",
            "Costco Business Center": "Costco Wholesale",
            "Nob Hill": "Nob Hill Foods",
            "Rancho San Miguel": "Rancho San Miguel Market",
            "Mi Rancho Supermarket": "Mi Rancho Market",
            "Mi Rancho Carniceria": "Mi Rancho Market",
            "Mi Rancho Bayside Market": "Mi Rancho Market",
            "Stater Bros": "Stater Bros. Market",
            "Stater Bros.": "Stater Bros. Market",
            "Stater Bros Market": "Stater Bros. Market",
            "Stater Brothers Market": "Stater Bros. Market",
            "Super A Foods": "Super A Foods",
            "State Foods Supermarket": "State Foods Supermarket",
            "State Foods Chowchilla": "State Foods Supermarket",
            "State Foods Coalinga": "State Foods Supermarket",
            "State Foods Madera": "State Foods Supermarket",
            "State Foods Supemarket": "State Foods Supermarket",
            "Big Saver Food": "Big Saver Foods",
            "Sav Mor Foods": "Sav Mor Foods",
            "Mother Earth Nutrition": "Mother Earth Nutrition",
            "Mother's Nutritional Center": "Mother's Nutritional Center",
            "Mother's Nutritional Center Mnc": "Mother's Nutritional Center",
            "Mother'S Nutritonal Center": "Mother's Nutritional Center",
            "Mother'S Nutritional Center": "Mother's Nutritional Center",
            "Mommys Nutritional Center": "Mother's Nutritional Center",
            "Mnc": "Mother's Nutritional Center",
            "Mothers & Kids Nutrition": "Mother's Nutritional Center",
            "Baby Nutrition": "Baby Nutrition",
            "Baby'S Nutrition": "Baby Nutrition",
            "Baby Nutritional Care": "Baby Nutrition",
            "Baby Nutrition Shop": "Baby Nutrition",
            "Basic Nutrition": "Basic Nutrition",
            "First Step Nutrition": "First Step Nutrition",
            "Kids Nutricare": "Kids Nutricare",
            "Eatwell Nutrition": "Eatwell Nutrition",
            "Health Nutrition": "Health Nutrition",
            "Prime Years Nutrition": "Prime Years Nutrition",
            "Prime Time Nutricion": "Primetime Nutrition",
            "Lucky California": "Lucky",
            "Lucky Market": "Lucky",
            "Costco Wholesale": "Costco Wholesale",
            "El Super": "El Super",
            "Vallarta Supermarket": "Vallarta Supermarket",
            "Pavilions": "Pavilions",
            "Sprouts": "Sprouts Farmers Market",
            "Northgate Gonzalez Market": "Northgate Market",
            "Viva Supermarket": "Viva Market",
            "Foods": "Foods Co",
            "Foods Co": "Foods Co",
            "Cost Less Food Company": "Costco Wholesale",
            "Smart & Final Store": "Smart & Final",
            "Smart & Final Stores": "Smart & Final",
            "La Superior": "Superior Grocers",
            "Superior Market": "Superior Grocers",
            "La Superior Mercados": "Superior Grocers",
            "The Market By Superior": "Superior Grocers",
            "Grocery Outlet": "Grocery Outlet",
            "Grocery Outlet Bargain Market": "Grocery Outlet",
            "Super King Market": "Super King Market",
            "Jons Market": "Jons Market",
            "Zion Mart": "Zion Market",
            "Zion Market": "Zion Market",
            "La Mexicana Meat Market": "La Mexicana Market",
            "La Mexicana Market And Bakery": "La Mexicana Market",
            "Carniceria La Mexicana": "La Mexicana Market",
            "Guadalajara Meat Market": "Guadalajara Market",
            "Guadalajara Market": "Guadalajara Market",
            "El Rancho Market": "El Rancho Market",
            "El Rancho Supermercado": "El Rancho Market",
            "Santa Fe Foods": "Santa Fe Foods",
            "La Favorita Market": "La Favorita Market",
            "Amigos Market": "Amigos Market",
            "Amigos Food Market": "Amigos Market",
            "3 Amigos Market": "Amigos Market",
            "One Stop Market": "One Stop Market",
            "Beyond Food Mart": "Beyond Food Mart",
            "Bonfare Market": "Bonfare Market",
            "Holiday Market": "Holiday Market",
            "Nugget Market": "Nugget Market",
            "Lost Nugget Market": "Nugget Market",
            "Verdugo Market": "Verdugo Market",
            "City Market": "City Market",
            "Sam's Market": "Sam's Market",
            "Sams Mart": "Sam's Market",
            "Ray's Food Place": "Ray's Food Place",
            "99 Ranch Market": "99 Ranch Market",
            "168 Market": "168 Market",
            "Barons Market": "Barons Market",
            "New Leaf Community Market": "New Leaf Community Market",
            "Silver Creek Community Market By New Leaf": "New Leaf Community Market",
            "Mollie Stone's Market": "Mollie Stone's Market",
            "Andronico's": "Andronico's",
            "Rancho San Miguel Market": "Rancho San Miguel Market",
            "Quickeroo": "Quickeroo",
            "Tropicana Supermarket": "Tropicana Supermarket",
            "Pacific Market": "Pacific Market",
            "La Raza Market": "La Raza Market",
            "La Perla Tapatia": "La Perla Tapatia",
            "La Bodega Ranch Market": "La Bodega Market",
            "La Bodega Market": "La Bodega Market",
            "La Plaza Market": "La Plaza Market",
            "La Hacienda Market": "La Hacienda Market",
            "La Esperanza Market": "La Esperanza Market",
            "La Cachanilla": "La Cachanilla",
            "La Tapatia Market": "La Tapatia Market",
            "La Tiendita": "La Tiendita",
            "La Loma": "La Loma Market",
            "La Loma Produce": "La Loma Market",
            "La Paloma Market": "La Paloma Market",
            "La Familia Market": "La Familia Market",
            "La Princesa Market": "La Princesa Market",
            "El Sol Market": "El Sol Market",
            "El Toro Market": "El Toro Market",
            "El Milagro Market": "El Milagro Market",
            "El Rey Market": "El Rey Market",
            "Mercado El Rey": "El Rey Market",
            "El Torito Market": "El Torito Market",
            "Calimex Market": "Calimex Market",
            "Azteca Market": "Azteca Market",
            "Latino Market": "Latino Market",
            "Carniceria Rancho Grande": "Carniceria Rancho Grande",
            "Carniceria Del Valle": "Carniceria Del Valle",
            "Carniceria La Oaxaquena": "Carniceria La Oaxaquena",
            "Carniceria Colima": "Carniceria Colima",
            "Colimas Carniceria Y Taqueria": "Carniceria Colima",
            "Chapala Market": "Chapala Market",
            "Fiesta Market": "Fiesta Market",
            "Primo Market": "Primo Market",
            "Pioneer Market": "Pioneer Market",
            "Tower Market": "Tower Market",
            "Rainbow Market": "Rainbow Market",
            "Sky Market": "Sky Market",
            "Sunshine Market": "Sunshine Market",
            "Royal Market": "Royal Market",
            "Quality Market": "Quality Market",
            "Payless Market": "Payless Market",
            "Oasis Market": "Oasis Market",
            "Oliver's Market": "Oliver's Market",
            "Harvest Market": "Harvest Market",
            "Friendly Market": "Friendly Market",
            "Lucky Market": "Lucky Market",
            "Save More Market": "Save More Market",
            "Quick Stop Market": "Quick Stop Market",
            "Quickmart": "Quickmart",
            "Express Mart": "Express Mart",
            "Fast And Easy Mart": "Fast And Easy Mart",
            "Stop And Shop Market": "Stop And Shop Market",
            "Valley Food Market": "Valley Food Market",
            "Corner Market": "Corner Market",
            "Sierra Market": "Sierra Market",
            "Country Market": "Country Market",
            "Viva Market": "Viva Market",
            "California Market": "California Market",
            "Plaza Market": "Plaza Market",
            "Best Market": "Best Market",
            "Star Market": "Star Market",
            "Neighborhood Market": "Neighborhood Market",
            "Community Market": "Community Market",
            "Santa Cruz Market": "Santa Cruz Market",
            "San Marcos Market": "San Marcos Market",
            "Lola's Market": "Lola's Market",
            "Joe's Market": "Joe's Market",
            "Jerry's Market": "Jerry's Market",
            "Harry's Market": "Harry's Market",
            "John's Market": "John's Market",
            "Tony's Market": "Tony's Market",
            "Young's Market": "Young's Market",
            "Bill's Market": "Bill's Market",
            "Bob's Market": "Bob's Market",
            "Bobs Market": "Bob's Market",
            "S & S Market": "S & S Market",
            "S & K Mini Mart": "S & K Mini Mart",
            "A-1 Market": "A-1 Market",
            "Abc Supermarket": "ABC Supermarket",
            "Abc Market": "ABC Market",
            "North Park Produce": "North Park Produce",
            "Saveco": "Saveco",
            "Manolo Farmers Market": "Manolo Farmers Market",
            "R-Ranch Market": "R-Ranch Market",
            "Los Primos Market": "Los Primos Market",
            "Los Amigos Market": "Los Amigos Market",
            "Gonzalez Meat Market": "Gonzalez Meat Market",
            "B & B Market": "B & B Market",
            "Asian Market": "Asian Market",
            "Farmers Market": "Farmers Market",
            # --- Chains found in thorough audit ---
            "International Food Mart": "International Market",
            "International Food Market": "International Market",
            "International Foods": "International Market",
            "International Produce Market": "International Market",
            "Asia Foods": "Asian Market",
            "Asia Market": "Asian Market",
            "Asia Mart": "Asian Market",
            "Asia Supermarket": "Asian Market",
            "Asian Mart": "Asian Market",
            "Asian Food Center": "Asian Market",
            "Asian Food Market": "Asian Market",
            "Foothill Food Mart": "Foothill Market",
            "Foothill Produce": "Foothill Market",
            "El Toro Loco Market": "El Toro Loco",
            "El Toro Loco Meat Market": "El Toro Loco",
            "El Toro Loco Supermercado": "El Toro Loco",
            "Jiffy Food": "Jiffy Mart",
            "Jiffy Food Store": "Jiffy Mart",
            "Jiffy Food Mart": "Jiffy Mart",
            "Jiffy Mart": "Jiffy Mart",
            "Hernandez Grocery Market": "Hernandez Market",
            "Hernandez Meat Market": "Hernandez Market",
            "Hernandez Produce": "Hernandez Market",
            "Mi Ranchito Meat Market": "Mi Ranchito Market",
            "Mi Ranchito Produce": "Mi Ranchito Market",
            "Gold Star Grocery": "Gold Star Mart",
            "Gold Star Market": "Gold Star Mart",
            "Gold Star Mart": "Gold Star Mart",
            "Snappy Food Mart": "Snappy Mart",
            "Snappy Food Store": "Snappy Mart",
            "Snappy Mart": "Snappy Mart",
            "Union Food Market": "Union Market",
            "Union Plaza Market": "Union Market",
            "California Food Mart": "California Market",
            "California Grocery": "California Market",
            "California Meat Market": "California Market",
            "California Produce Market": "California Market",
            "La Fortuna Market": "La Fortuna Market",
            "La Fortuna Meat Market": "La Fortuna Market",
            "La Fiesta Foods": "La Fiesta Market",
            "La Fiesta Meat Market": "La Fiesta Market",
            "Lucky 7 Food Mart": "Lucky 7",
            "Lucky 7 Food Store": "Lucky 7",
            "Lucky 7 Supermarket": "Lucky 7",
            "El Mercadito Meat Market": "El Mercadito",
            "El Mercadito Market": "El Mercadito",
            "Super Star Food Store": "Super Star Market",
            "Super Star Food Mart": "Super Star Market",
            "Super Star Market": "Super Star Market",
            "Central Food Mart": "Central Market",
            "Central Mart": "Central Market",
            "Central Meat Market": "Central Market",
            "Central Store": "Central Market",
            "Shop N Go Food Store": "Shop N Go Market",
            "Shop N Go Market": "Shop N Go Market",
            "Discount Grocery": "Discount Mart",
            "Discount Mart": "Discount Mart",
            "M & M Grocery": "M & M Market",
            "M & M Meat Market": "M & M Market",
            "Prince Food & Gas": "Prince Market",
            "Prince Food Mart": "Prince Market",
            "Prince Mart": "Prince Market",
            "Rancho Mart": "Rancho Market",
            "Rancho Meat Market": "Rancho Market",
            "Rancho Produce Market": "Rancho Market",
            "Imperial Food Supermarket": "Imperial Market",
            "Imperial Liquor": "Imperial Market",
            "La Guadalupana Meat Market": "La Guadalupana Market",
            "Stockton Food And Gas": "Stockton Market",
            "Stockton Supermercado": "Stockton Market",
            "Grand Foods Market": "Grand Market",
            "Cali Mart": "Cali Market",
            "Cali Produce": "Cali Market",
            "Marina Grocery": "Marina Market",
            "Los Amigos Food Center": "Los Amigos Market",
            "Los Amigos Meat Market": "Los Amigos Market",
            "Odessa Grocery": "Odessa Market",
            "Royal Food": "Royal Market",
            "Royal Food Market": "Royal Market",
            "Maxi Foods": "Maxi Mart",
            "Maxi Mart": "Maxi Mart",
            "Mercado Latino": "Mercado Latino",
            "Mercado Latino Market": "Mercado Latino",
            "Carniceria Gonzalez": "Carniceria Gonzalez",
            "Carniceria Gonzalez Meat Market": "Carniceria Gonzalez",
            "City Food & Gas": "City Market",
            "City Food Market": "City Market",
            "City Mart": "City Market",
            "Fiesta Food Market": "Fiesta Market",
            "Fiesta Supermarket": "Fiesta Market",
            "Rodeo Grocery": "Rodeo Market",
            "Rodeo Meat Market": "Rodeo Market",
            "Korner Grocery": "Korner Market",
            "Uno Produce Market": "Uno Market",
            "Uno Supermarket": "Uno Market",
            "Uno Liquor Market": "Uno Market",
            "Lunardi Foods": "Lunardi's Market",
            "Lunardi Market": "Lunardi's Market",
            "Alex Food Mart": "Alex Market",
            "Alex Grocery": "Alex Market",
            "Cedar Food Mart": "Cedar Market",
            "Star Grocery": "Star Market",
            "Star Mart": "Star Market",
            "Big Valley Food": "Big Valley Market",
            "Big Valley Supermarket": "Big Valley Market",
            "H Food Mart": "H Mart",
            "H Mart": "H Mart",
            "Ok Food Mart": "OK Market",
            "Ok Market": "OK Market",
            "OK Market": "OK Market",
            "Canyon Food Mart": "Canyon Market",
            "La Venadita Meat Market": "La Venadita",
            "Al's Food Market": "Al's Market",
            "Al's Market": "Al's Market",
            "Sams Mini Market": "Sams Mini Mart",
            "Sams Mini Mart": "Sams Mini Mart",
            "Sams Mini Market": "Sams Mini Mart",
            "El Pueblo Meat Market": "El Pueblo Market",
            "El Pueblo Produce Market": "El Pueblo Market",
            "El Pueblo Supermercado": "El Pueblo Market",
            "Santa Fe Mercado": "Santa Fe Foods",
            "El Ranchito Meat Market": "El Ranchito Market",
            "Los Portales Meat Market": "Los Portales",
            "El Ahorro Market": "El Ahorro",
            "El Ahorro Store": "El Ahorro",
            "El Mexicano Market": "El Mexicano Market",
            "El Mexicano Meat Market": "El Mexicano Market",
            "El Campeon Carniceria": "El Campeon",
            "El Campeon Carniceria Market": "El Campeon",
            "Sunshine Food Mart": "Sunshine Market",
            "Sunshine Food & Gas": "Sunshine Market",
            "Sunshine Food And Gas": "Sunshine Market",
            "Sanchez Grocery": "Sanchez Market",
            "Sanchez Meat Market": "Sanchez Market",
            "Fast & Easy Mart": "Fast & Easy Mart",
            "Ramirez Produce": "Ramirez Market",
            "A-1 Food & Gas Mart": "A-1 Market",
            "A-1 Food Store": "A-1 Market",
            "A-1 Mart": "A-1 Market",
            "San Diego Food Market": "San Diego Market",
            "Mi Tiendita": "Mi Tiendita",
            "Mi Tiendita Market": "Mi Tiendita",
            "Bonita Foods": "Bonita Market",
            "Choice Food Market": "Choice Market",
            "El Mercado": "El Mercado",
            "El Mercado Market": "El Mercado",
            "Fresno Food Mart": "Fresno Market",
            "Fresno Mart": "Fresno Market",
            "Sunny Food Market": "Sunny Market",
            "Sunny Market": "Sunny Market",
            "Mar-Val Food": "Mar-Val Market",
            "Mar-Val Food Store": "Mar-Val Market",
            "El Charrito Meat Market": "El Charrito Market",
            "Pacific Food Mart": "Pacific Market",
            "Pacific Supermarket": "Pacific Market",
            "La Esperanza Food Center": "La Esperanza Market",
            "El Rey Meat Market": "El Rey Market",
            "El Rey Supermarket": "El Rey Market",
            "El Rey Supermercado": "El Rey Market",
            "El Charro Supermarket": "El Charro Market",
            "El Charro Meat Market": "El Charro Market",
            "El Charro Supermercado": "El Charro Market",
            "La Raza Deli Market": "La Raza Market",
            "La Raza Meat Market": "La Raza Market",
            "La Perla Market": "La Perla Tapatia",
            "Lupita's Market": "Lupita's Market",
            "Lupita's Supermarket": "Lupita's Market",
            "Mission Food Center": "Mission Market",
            "Kerman Food Center": "Kerman Market",
            "Kerman Food Market": "Kerman Market",
            "Kerman Food Mart": "Kerman Market",
            "A&M Market": "A&M Market",
            "A&M Food Mart": "A&M Market",
            "Indian Market": "Indian Market",
            "Indian Supermarket": "Indian Market",
            "Day & Night Food Mart": "Day & Night Market",
            "Day & Night Market": "Day & Night Market",
            "Brothers Food Mart": "Brothers Market",
            "Brothers Market": "Brothers Market",
            "Jk Market": "JK Market",
            "JK Food Store": "JK Market",
            "JK Market": "JK Market",
            "Las Palmas Produce": "Las Palmas Market",
            "Lee's Food Market": "Lee's Market",
            "Lee's Grocery": "Lee's Market",
            "Michoacan Meat Market": "Michoacan Market",
            "Michoacan Produce": "Michoacan Market",
            "Michoacan Produce Market": "Michoacan Market",
            "Super Discount Market": "Super Discount",
            "Prime Meat Carniceria": "Prime Market",
            "Jalisco Meat Market": "Jalisco Market",
            "Jalisco Produce Market": "Jalisco Market",
            "A Food Mart": "A Mart",
            "A Mart": "A Mart",
            "Airport Grocery": "Airport Market",
            "Valley Food": "Valley Market",
            "Valley Food Supermarket": "Valley Market",
            "Valley Foods": "Valley Market",
            "Valley Foods Supermarket": "Valley Market",
            "Valley Food Mart": "Valley Market",
            "Family Food Market": "Family Market",
            "Family Food Mart": "Family Market",
            "Family Foods": "Family Market",
            "Family Mart": "Family Market",
            "El Rancho Foods": "El Rancho Market",
            "El Rancho Grocery Market": "El Rancho Market",
            "El Rancho Supermarket": "El Rancho Market",
            "El Rancho Carniceria": "El Rancho Market",
            "El Rancho Meat Market": "El Rancho Market",
            "El Rancho Produce": "El Rancho Market",
            "El Toro Foods": "El Toro Market",
            "El Toro Bravo Market": "El Toro Market",
            "Vallarta Supermarkets": "Vallarta Supermarket",
            "Vallarta Supermarkets.Com": "Vallarta Supermarket",
            "Puerto Vallarta Market": "Vallarta Supermarket",
            "Super La Favorita": "La Favorita Market",
            "La Favorita Supermarket": "La Favorita Market",
            "Amigos Food Market": "Amigos Market",
            "Amigos Mini Mart": "Amigos Market",
            "Carniceria Dos Amigos": "Amigos Market",
            "One Stop Food Mart": "One Stop Market",
            "One Stop Corner Market": "One Stop Market",
            "One Stop African Market": "One Stop Market",
            "Arrwa One Stop Market": "One Stop Market",
            "Super King Food Center": "Super King Market",
            "Super King Food Ctr": "Super King Market",
            "Barons Marketplace": "Barons Market",
            "La Tropicana Market": "Tropicana Supermarket",
            "Tropicana Market": "Tropicana Supermarket",
            "Tropicana Foods": "Tropicana Supermarket",
            "La Raza Meat Market #": "La Raza Market",
            "Super Mercado La Raza": "La Raza Market",
            "La Perla Tapatia Meat Market": "La Perla Tapatia",
            "La Bodega Farmers Market": "La Bodega Market",
            "La Bodega Latina": "La Bodega Market",
            "La Bodega Meat Produce": "La Bodega Market",
            "La Hacienda Meat Market": "La Hacienda Market",
            "La Hacienda Super Mercado": "La Hacienda Market",
            "La Esperanza Meat Market": "La Esperanza Market",
            "La Esperanza Market Y Taqueria": "La Esperanza Market",
            "Carniceria La Esperanza": "La Esperanza Market",
            "El Sol Meat Market": "El Sol Market",
            "Carniceria Del Sol": "El Sol Market",
            "Del Sol": "El Sol Market",
            "Azteca Meat Market": "Azteca Market",
            "Andrews Azteca Market": "Azteca Market",
            "Azteca 99 Cents Plus": "Azteca Market",
            "Mercado Latino": "Latino Market",
            "Latinos Market": "Latino Market",
            "Latinos Meat Market": "Latino Market",
            "Fiesta Latino Market": "Latino Market",
            "Super Fiesta Market": "Fiesta Market",
            "Fiesta Foods & Meat Market": "Fiesta Market",
            "Primo Food Store": "Primo Market",
            "El Primo Market": "Primo Market",
            "Mas Primos Market": "Primo Market",
            "Los Primos Market & Liquor": "Los Primos Market",
            "Tower Gas & Mini Mart": "Tower Market",
            "Tower Market And Deli": "Tower Market",
            "Rainbow Seafood Market": "Rainbow Market",
            "Rainbow Grocery": "Rainbow Market",
            "Skyline Mini Mart": "Skyline Market",
            "Skyway Gas & Food": "Skyline Market",
            "Skyline Market": "Skyline Market",
            "Royal International Market": "Royal Market",
            "Royal Gas And Food": "Royal Market",
            "Harvest Natural Foods": "Harvest Market",
            "Fresh Harvest Market": "Harvest Market",
            "Harvest International Market": "Harvest Market",
            "Fast & Friendly Market": "Fast & Friendly Market",
            "New Friendly Market": "Friendly Market",
            "Davids Friendly Market": "Friendly Market",
            "Market Express": "Express Market",
            "Express Gas Mart": "Express Mart",
            "J S Express Market": "Express Mart",
            "Premier Market Express": "Express Mart",
            "Express Market": "Express Mart",
            "Quick Food & Gas": "Quick Mart",
            "Quick Food Market": "Quick Mart",
            "Quick Food Store": "Quick Mart",
            "Quick Mart": "Quick Mart",
            "Valley Food And Gas": "Valley Market",
            "Catheys Valley Food And Gas": "Valley Market",
            "4 Corners Market": "Corner Market",
            "Djs Corner Market": "Corner Market",
            "H & G Corner Market": "Corner Market",
            "The Corner Market": "Corner Market",
            "Alta Sierra Market": "Sierra Market",
            "Sierra Hills Market": "Sierra Market",
            "Tresierras Supermarket": "Sierra Market",
            "Acton Market Country Store": "Country Market",
            "Deep Creek Country Market": "Country Market",
            "Countryside Market": "Country Market",
            "Lippys Country Mart": "Country Market",
            "Pelican Plaza Grocery": "Plaza Market",
            "De Soto Plaza Jr Market": "Plaza Market",
            "Citrus Plaza Market": "Plaza Market",
            "Nates Market Plaza": "Plaza Market",
            "5 Star Market": "Star Market",
            "All Star Market": "Star Market",
            "Seven Star Market": "Star Market",
            "Jrs Neighborhood Market": "Neighborhood Market",
            "County Line Neighborhood Market": "Neighborhood Market",
            "Neighborhood Grocery": "Neighborhood Market",
            "Keo Neighborhood Market": "Neighborhood Market",
            "Cornucopia Community Market": "Community Market",
            "Dahlia & Sage Community Market": "Community Market",
            "Fresno Community Market": "Community Market",
            "Santa Cruz Market Sc": "Santa Cruz Market",
            "Mercado Santa Cruz": "Santa Cruz Market",
            "Joes Food Mart": "Joe's Market",
            "Joes Handy Market": "Joe's Market",
            "Johnnys Market": "John's Market",
            "Johnnie's Supermarket": "John's Market",
            "Johnny Quik Food Store": "John's Market",
            "Tonys Fresh Market": "Tony's Market",
            "Tonys Mini Mart": "Tony's Market",
            "Tony Star Gas And Food": "Tony's Market",
            "Eddies Market": "Eddie's Market",
            "Garcia's Market": "Garcia's Market",
            "Jacks Market": "Jack's Market",
            "Murphys Market": "Murphy's Market",
            "Five Star Market": "Star Market",
            "Sunset Market": "Sunset Market",
            "Apple Tree Market": "Apple Tree Market",
            "Carnival Supermarket": "Carnival Market",
            "Mariposa Market": "Mariposa Market",
            "T S Emporium": "T S Emporium",
            "Park View Market": "Park View Market",
            "Noor Market": "Noor Market",
            "The Meat Market": "The Meat Market",
            "Quik Mart": "Quik Mart",
            "La Michoacana Market": "La Michoacana Market",
            "Afghan Market": "Afghan Market",
            "La Morenita Market": "La Morenita Market",
            "Kings Market": "Kings Market",
            "Baja Ranch Market": "Baja Ranch Market",
            "Marina Food": "Marina Market",
            "Manila Oriental Market": "Manila Oriental Market",
            "Quick Pick Market": "Quick Pick Market",
            "Green Valley Market": "Green Valley Market",
            "La Cadena Market": "La Cadena Market",
            "Evergreen Market": "Evergreen Market",
            "Mountain Market": "Mountain Market",
            "Valley Market": "Valley Market",
            "El Pueblo Food": "El Pueblo Market",
            "Full Stop Market": "Full Stop Market",
            "Las Espuelas": "Las Espuelas",
            "Shop & Save Market": "Shop & Save Market",
            "Shop N Save Market": "Shop & Save Market",
            "C & C Market": "C & C Market",
            "E Market": "E Market",
            "Main Market": "Main Market",
            "Main Street Market": "Main Street Market",
            "Perez Market": "Perez Market",
            "Rose Market": "Rose Market",
            "Us Market": "Us Market",
            "Js Market": "JS Market",
            "Fast Mart": "Fast Mart",
            "Sonora Market": "Sonora Market",
            "Lion Food Center": "Lion Food Center",
            "El Torito Meat Market": "El Torito Market",
            "La Aurora Market": "La Aurora Market",
            "U-Save Market": "U-Save Market",
            "Kwik Stop Market": "Kwik Stop Market",
            "Economy Market": "Economy Market",
            "Fresh Produce": "Fresh Produce",
            "Handy Market": "Handy Market",
            "Lakeside Market": "Lakeside Market",
            "4 Way Meat Market": "4 Way Meat Market",
            "Town & Country Market": "Town & Country Market",
            "Juniors Market": "Juniors Market",
            "El Pacifico Market": "El Pacifico Market",
            "Mediterranean Market": "Mediterranean Market",
            "Sierra Minit Mart": "Sierra Minit Mart",
            "Bi-Rite Market": "Bi-Rite Market",
            "Namaste Plaza": "Namaste Plaza",
            "Coconut Hill": "Coconut Hill",
            "88 Manor Market": "88 Manor Market",
            "Arteagas Food Center": "Arteagas Food Center",
            "Los Altos Meat Market": "Los Altos Meat Market",
            "R-N Market": "R-N Market",
            "Jensen's Finest Foods": "Jensen's Market",
            "Berkeley Bowl Produce": "Berkeley Bowl",
            "Lazy Acres": "Lazy Acres",
            "Major Market": "Major Market",
            "Lassen Market": "Lassen Market",
            "Amapola Deli & Market": "Amapola Market",
            "Ranch Market": "Ranch Market",
            "Food Stop": "Food Stop",
            "Discount Market": "Discount Mart",
            "Market Plus": "Market Plus",
            "North Coast Cooperative": "North Coast Market",
            "India Spices": "Indian Market",
            "Indian Bazaar": "Indian Market",
            "Albertson's": "Albertsons",
            "Winco": "Winco Foods",
            "Winco Foods": "Winco Foods",
            "Save Mart Foods": "Save Mart",
            "Save Mart Market": "Save Mart",
            "Bel Air Mart": "Bel Air",
            "Bel Air Market": "Bel Air",
            "Redwood Store": "Redwood Market",
            "Redwoods Market": "Redwood Market",
            "Redwood City Grocery Outlet": "Grocery Outlet",
            "Chavez Mini Mart": "Chavez Supermarket",
            "Chavez Meat Market": "Chavez Supermarket",
            "Pak N Save": "Pak 'N Save",
            "Super Carniceria Mi Rancho": "Mi Rancho Market",
            "Mi Rancho Market Sm": "Mi Rancho Market",
            "La Mexicana Carniceria Y Taqueria": "La Mexicana Market",
            "La Mexicana Grocery": "La Mexicana Market",
            "Rancho La Mexicana Carniceria": "La Mexicana Market",
            "Rancho La Mexicana Market": "La Mexicana Market",
            "Panaderia Guadalajara": "Guadalajara Market",
            "Mi Guadalajara Meat Market": "Guadalajara Market",
            "La Carniceria Guadalajara": "Guadalajara Market",
            "El Nuevo Guadalajara Meat Market": "Guadalajara Market",
            "Del Rancho Market": "El Rancho Market",
            "Santa Fe Mercados": "Santa Fe Foods",
            "Santa Fe 1 Stop Market": "Santa Fe Foods",
            "Amigo Market": "Amigos Market",
            "Supermercado Mi Tierra": "Mi Tierra Market",
            "Jons Marketplace": "Jons Market",
            "Lunardi's Market": "Lunardi's Market",
            "Mollie Stone's Market": "Mollie Stone's Market",
            "Andronico's": "Andronico's",
            "Rancho San Miguel Market": "Rancho San Miguel Market",
        }
        return aliases.get(name, name)

    norm_counts = Counter(normalize_banner(s.get("banner", "")) for s in all_stores)
    major_banners = {name for name, count in norm_counts.items() if count >= 3}
    for s in all_stores:
        norm = normalize_banner(s.get("banner", ""))
        if norm in major_banners:
            s["banner_group"] = norm
        else:
            s["banner_group"] = "Misc."

    all_stores.sort(key=lambda s: (s.get("city", ""), s.get("banner", "")))

    # --- Build summary ---
    store_type_counts = Counter(s.get("store_type", "") for s in all_stores)
    banner_group_counts = Counter(s.get("banner_group", "") for s in all_stores)

    summary = {
        "store_count_total": len(all_stores),
        "store_count_milkpep_tda": len(ca_stores),
        "store_count_snap_new": len(snap_stores),
        "store_type_counts": dict(sorted(store_type_counts.items())),
        "banner_group_counts": dict(sorted(banner_group_counts.items())),
        "major_banners": sorted(major_banners),
        "states": {"CA": len(all_stores)},
    }

    output = {
        "stores": all_stores,
        "meta": {
            "summary": summary,
        },
    }

    OUTPUT_PATH.write_text(json.dumps(output, indent=2))
    print(f"CA MilkPEP/TDA stores: {len(ca_stores)}")
    print(f"New SNAP stores: {len(snap_stores)}")
    print(f"Total: {len(all_stores)}")
    print()
    print("Store type counts:")
    print(json.dumps(dict(sorted(store_type_counts.items())), indent=2))
    print()
    print(f"Written to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
